### ISSUE TITLE
Make the script compatible with Python 3

### ISSUE THREAD

**Issue by jaroslawhartman** [jaroslawhartman/withings-garmin-v2#8]
Follow up of https://github.com/jaroslawhartman/withings-garmin-v2/issues/7#issuecomment-378719926

**Comment by magnific0** [comment]
Hi @jaroslawhartman it's great to see you're so actively maintaining this repo.

Regarding Python 3 support, my project [nokia-weight-sync](https://github.com/magnific0/nokia-weight-sync) uses the same ```garmin.py```, ```fit.py``` and ```sessioncache.py``` as yours. The former two I have adapted for Python 3. I think it would be a good starting point for a Python 3 port. Apart from the Python 3 compatibility I copied the exception class definitions into ```garmin.py``` so that they are actually defined.

Let me know if you need any help with the port!

**Comment by jaroslawhartman** [comment]
Thank you @magnific0 !

Somehow I forgotten about this comment and that you actually have fixed these three Python files and I've done same work to reinvent the wheel...

Anyway, it seems to work now.... 

Thank you,
Jarek
